samtools view pti096_clean_aln_pe_unique.bam |wc -l > t.log
samtools view pti103_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view pti105_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view pti177_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view pti183_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view pti184_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view pti185_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view pti186_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view pti208_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view pti220_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view pti247_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view pti248_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view pti262_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view pti269_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view pti270_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view pti272_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view pti273_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view pti292_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view pti303_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view pti304_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view pti305_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view pti306_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view pti307_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view pti330_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view pti331_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view pti332_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view RFET0002_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view RFET0003_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view RFET0005_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view RFET0006_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view RFET0007_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view RFET0011_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view SRR836354_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view SRR836361_clean_aln_pe_unique.bam |wc -l >> t.log
samtools view SRR836372_clean_aln_pe_unique.bam |wc -l >> t.log
