samtools index A3_merge.bam &
samtools index AMO3305_merge.bam &
samtools index AMO3306_merge.bam &
samtools index AMO3307_merge.bam &
samtools index AMO3308_merge.bam &
samtools index AMO3311_merge.bam &
samtools index HNSD_merge.bam &
samtools index HPS_merge.bam &
samtools index M2_merge.bam &
samtools index NGH1_merge.bam &
samtools index PtiP121_merge.bam &
samtools index Y14_merge.bam &
samtools index Y15_merge.bam &
samtools index Y3_merge.bam &
samtools index Y7_merge.bam &
