./run_psmc_pipe.sh HPS auto_9th.vcf &
./run_psmc_pipe.sh NGH2 auto_9th.vcf &
./run_psmc_pipe.sh pti096 auto_9th.vcf &
./run_psmc_pipe.sh pti103 auto_9th.vcf &
./run_psmc_pipe.sh pti217 auto_9th.vcf &
./run_psmc_pipe.sh pti220 auto_9th.vcf &
./run_psmc_pipe.sh pti248 auto_9th.vcf &
./run_psmc_pipe.sh pti306 auto_9th.vcf &
./run_psmc_pipe.sh PTV06 auto_9th.vcf &
./run_psmc_pipe.sh PTV02_old auto_9th.vcf &
./run_psmc_pipe.sh PTV17_old auto_9th.vcf &
./run_psmc_pipe.sh RFET0003 auto_9th.vcf &
./run_psmc_pipe.sh RUSA21 auto_9th.vcf &
